//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteASP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int idProject { get; set; }
        public int idUser { get; set; }
        public string title { get; set; }
        public string tag { get; set; }
        public string description { get; set; }
        public System.DateTime timeOfPost { get; set; }
        public System.DateTime lastTimeChanged { get; set; }
        public int numberOfLikes { get; set; }
        public string mainImageLink { get; set; }
        public Nullable<int> idLastUserChange { get; set; }
        public Nullable<System.DateTime> LastTimeChange { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual User User { get; set; }
    }
}
