//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteASP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int idUser { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int idRole { get; set; }
        public System.DateTime timeOfRegistration { get; set; }
        public string verificationCode { get; set; }
        public int idStatus { get; set; }
        public Nullable<int> idLastUserChange { get; set; }
        public Nullable<System.DateTime> LastTimeChange { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual Role Role { get; set; }
        public virtual Status Status { get; set; }
    }
}
